Issue 124 add java nio path support
jakartaee/jaf-api pull request #126
Opened 2023-04-02 13:49 UTC by rmcdouga

PR supporting Issue #124

2023-04-02 14:29 UTC, rmcdouga commented
I see the builds are failing due to Javadoc.  I will correct this.  Also, it seems like the eca issue is related to the multiple email addresses I have on my GitHub account.  I have accepted the ECA but the automated test seems to be confused.  I will see what can be done.

2023-04-03 07:17 UTC, lukasj requested changes
in general, looks good, yet some fine-tunning is needed:

* avoid using tabs and stick with current formatting
* reformatting comments as part of the change does not make reviewer's life easier
* copyright year should be updated
* change should be noted in the spec document, at least in [the changelog](https://github.com/jakartaee/jaf-api/blob/master/spec/src/main/asciidoc/activation.adoc?plain=1#L878)

should marking `File` variants as deprecated be considered or do you propose to just keep them as they are for now?

2023-04-03 07:17 UTC, lukasj commented on api/src/main/java/jakarta/activation/FileDataSource.java
> +	 * @param file the file
param `file` does not match `path` argument in the constructor

2023-04-03 07:21 UTC, lukasj commented on api/src/main/java/jakarta/activation/MimetypesFileTypeMap.java
> +     * @param p the file {@Code Path}
tag names start with lower-case letter

2023-04-03 11:59 UTC, rmcdouga commented
> avoid using tabs and stick with current formatting
Should I go back and change it back to what it was.  Sorry, the formatting style seemed very old-school to me, so I thought I was making things better but I understand the value of consistency.  I am happy to change it back.

> reformatting comments as part of the change does not make reviewer's life easier
Understood.

> copyright year should be updated
Will do.

> change should be noted in the spec document, at least in [the changelog](https://github.com/jakartaee/jaf-api/blob/master/spec/src/main/asciidoc/activation.adoc?plain=1#L878)
Will do.

> should marking File variants as deprecated be considered or do you propose to just keep them as they are for now?
This is a tough call.  Personally, I would deprecate them however the JDK maintainers have seen fit not to deprecate File even though it has been superseded.  I decided to follow the JDK lead and since it is not deprecated in the JDK, to leave it undeprecated in this API.  As a compromise, I put a note in the Javadoc indicating that the Path version should be preferred.

2023-04-03 12:00 UTC, rmcdouga commented
> avoid using tabs and stick with current formatting
Should I go back and change it back to what it was.  Sorry, the formatting style seemed very old-school to me, so I thought I was making things better but I understand the value of consistency.  I am happy to change it back.

> reformatting comments as part of the change does not make reviewer's life easier
Understood.

> copyright year should be updated
Will do.

> change should be noted in the spec document, at least in [the changelog](https://github.com/jakartaee/jaf-api/blob/master/spec/src/main/asciidoc/activation.adoc?plain=1#L878)
Will do.

> should marking File variants as deprecated be considered or do you propose to just keep them as they are for now?
This is a tough call.  Personally, I would deprecate them however the JDK maintainers have seen fit not to deprecate File even though it has been superseded.  I decided to follow the JDK lead and since it is not deprecated in the JDK, to leave it undeprecated in this API.  As a compromise, I put a note in the Javadoc referring users to the

2023-04-04 10:16 UTC, lukasj commented
> > avoid using tabs and stick with current formatting
> 
> Should I go back and change it back to what it was. Sorry, the formatting style seemed very old-school to me, so I thought I was making things better but I understand the value of consistency. I am happy to change it back.

yes, please - avoid tabs for new stuff. The codebase should be updated in one go followed by the inclusion of the change in `.git-blame-ignore-revs`

wrt deprecation - OK, let's keep it as it is and do nothing in that area for now

wrt failing ECA check - last two commits were probably done through different username (...www...) which has not signedthe ECA; the first one seems to be fine (probably)... can you try to amend them?

2023-04-14 16:06 UTC, lukasj approved these changes
LGTM, thanks!

2023-04-30 10:20 UTC, merged